runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /.*
  script: cultchecker.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
# [END libraries]
